// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5KVOogXloFqx88B3fNMkoyk_zTOcqKY',
    appId: '1:187716026331:web:b40f97341d14ae55aaf1fe',
    messagingSenderId: '187716026331',
    projectId: 'spiderbot-c507b',
    authDomain: 'spiderbot-c507b.firebaseapp.com',
    databaseURL: 'https://spiderbot-c507b-default-rtdb.firebaseio.com',
    storageBucket: 'spiderbot-c507b.appspot.com',
    measurementId: 'G-LX33SC8YEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2GOZOXbsf6trK56f_CF-Xn8fL55O66-U',
    appId: '1:187716026331:android:633000abf81da86faaf1fe',
    messagingSenderId: '187716026331',
    projectId: 'spiderbot-c507b',
    databaseURL: 'https://spiderbot-c507b-default-rtdb.firebaseio.com',
    storageBucket: 'spiderbot-c507b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh19ibYnklD9jSG6y5hqXdYPEyvCjuXJA',
    appId: '1:187716026331:ios:796e3fbcbf3d6e54aaf1fe',
    messagingSenderId: '187716026331',
    projectId: 'spiderbot-c507b',
    databaseURL: 'https://spiderbot-c507b-default-rtdb.firebaseio.com',
    storageBucket: 'spiderbot-c507b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh19ibYnklD9jSG6y5hqXdYPEyvCjuXJA',
    appId: '1:187716026331:ios:796e3fbcbf3d6e54aaf1fe',
    messagingSenderId: '187716026331',
    projectId: 'spiderbot-c507b',
    databaseURL: 'https://spiderbot-c507b-default-rtdb.firebaseio.com',
    storageBucket: 'spiderbot-c507b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5KVOogXloFqx88B3fNMkoyk_zTOcqKY',
    appId: '1:187716026331:web:a26335531b4e6a2eaaf1fe',
    messagingSenderId: '187716026331',
    projectId: 'spiderbot-c507b',
    authDomain: 'spiderbot-c507b.firebaseapp.com',
    databaseURL: 'https://spiderbot-c507b-default-rtdb.firebaseio.com',
    storageBucket: 'spiderbot-c507b.appspot.com',
    measurementId: 'G-VNGLJWTQ49',
  );
}
